// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using BiologyRecognition.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace BiologyRecognition.Domain.DBContext;

public partial class SE1709_SWD392_G4_BiologyRecognitionSystemContext : DbContext
{
    public SE1709_SWD392_G4_BiologyRecognitionSystemContext()
    {
    }

    public SE1709_SWD392_G4_BiologyRecognitionSystemContext(DbContextOptions<SE1709_SWD392_G4_BiologyRecognitionSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Article> Articles { get; set; }

    public virtual DbSet<Artifact> Artifacts { get; set; }

    public virtual DbSet<ArtifactMedia> ArtifactMedia { get; set; }

    public virtual DbSet<ArtifactType> ArtifactTypes { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<Recognition> Recognitions { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    public virtual DbSet<UserAccount> UserAccounts { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Article>(entity =>
        {
            entity.HasKey(e => e.ArticleId).HasName("PK__Article__CC36F660ACD12EC7");

            entity.ToTable("Article");

            entity.Property(e => e.ArticleId).HasColumnName("article_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("title");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ArticleCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Article__Created__5812160E");

            entity.HasOne(d => d.ModifiedByNavigation).WithMany(p => p.ArticleModifiedByNavigations)
                .HasForeignKey(d => d.ModifiedBy)
                .HasConstraintName("FK__Article__Modifie__59063A47");

            entity.HasMany(d => d.Artifacts).WithMany(p => p.Articles)
                .UsingEntity<Dictionary<string, object>>(
                    "ArticleArtifact",
                    r => r.HasOne<Artifact>().WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ArticleAr__artif__5CD6CB2B"),
                    l => l.HasOne<Article>().WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ArticleAr__artic__5BE2A6F2"),
                    j =>
                    {
                        j.HasKey("ArticleId", "ArtifactId").HasName("PK__ArticleA__2631BC16FC99FE5C");
                        j.ToTable("ArticleArtifact");
                        j.IndexerProperty<int>("ArticleId").HasColumnName("article_id");
                        j.IndexerProperty<int>("ArtifactId").HasColumnName("artifact_id");
                    });
        });

        modelBuilder.Entity<Artifact>(entity =>
        {
            entity.HasKey(e => e.ArtifactId).HasName("PK__Artifact__A074A76F652CE003");

            entity.ToTable("Artifact");

            entity.Property(e => e.ArtifactId).HasColumnName("artifact_id");
            entity.Property(e => e.ArtifactTypeId).HasColumnName("artifact_type_id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ScientificName)
                .HasMaxLength(100)
                .HasColumnName("scientific_name");

            entity.HasOne(d => d.ArtifactType).WithMany(p => p.Artifacts)
                .HasForeignKey(d => d.ArtifactTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Artifact__artifa__52593CB8");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ArtifactCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Artifact__Create__534D60F1");

            entity.HasOne(d => d.ModifiedByNavigation).WithMany(p => p.ArtifactModifiedByNavigations)
                .HasForeignKey(d => d.ModifiedBy)
                .HasConstraintName("FK__Artifact__Modifi__5441852A");
        });

        modelBuilder.Entity<ArtifactMedia>(entity =>
        {
            entity.HasKey(e => e.ArtifactMediaId).HasName("PK__Artifact__6FE8719739A4926A");

            entity.Property(e => e.ArtifactMediaId).HasColumnName("artifactMedia_id");
            entity.Property(e => e.ArtifactId).HasColumnName("artifact_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("url");

            entity.HasOne(d => d.Artifact).WithMany(p => p.ArtifactMedia)
                .HasForeignKey(d => d.ArtifactId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ArtifactM__artif__5FB337D6");
        });

        modelBuilder.Entity<ArtifactType>(entity =>
        {
            entity.HasKey(e => e.ArtifactTypeId).HasName("PK__Artifact__DFAFE6909B8606A3");

            entity.ToTable("ArtifactType");

            entity.Property(e => e.ArtifactTypeId).HasColumnName("artifact_type_id");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.TopicId).HasColumnName("topic_id");

            entity.HasOne(d => d.Topic).WithMany(p => p.ArtifactTypes)
                .HasForeignKey(d => d.TopicId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ArtifactT__topic__4E88ABD4");
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapter__745EFE8776388B04");

            entity.ToTable("Chapter");

            entity.Property(e => e.ChapterId).HasColumnName("chapter_id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.SubjectId).HasColumnName("subject_id");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ChapterCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Chapter__Created__44FF419A");

            entity.HasOne(d => d.ModifiedByNavigation).WithMany(p => p.ChapterModifiedByNavigations)
                .HasForeignKey(d => d.ModifiedBy)
                .HasConstraintName("FK__Chapter__Modifie__45F365D3");

            entity.HasOne(d => d.Subject).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.SubjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Chapter__subject__440B1D61");
        });

        modelBuilder.Entity<Recognition>(entity =>
        {
            entity.HasKey(e => e.RecognitionId).HasName("PK__Recognit__73D1F5AD83C0894D");

            entity.ToTable("Recognition");

            entity.Property(e => e.RecognitionId).HasColumnName("recognition_id");
            entity.Property(e => e.AiResult).HasColumnName("ai_result");
            entity.Property(e => e.ArtifactId).HasColumnName("artifact_id");
            entity.Property(e => e.ConfidenceScore).HasColumnName("confidence_score");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image_url");
            entity.Property(e => e.RecognizedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("recognized_at");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("PENDING")
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Artifact).WithMany(p => p.Recognitions)
                .HasForeignKey(d => d.ArtifactId)
                .HasConstraintName("FK__Recogniti__artif__656C112C");

            entity.HasOne(d => d.User).WithMany(p => p.Recognitions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Recogniti__user___66603565");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subject__5004F66085C1E0A6");

            entity.ToTable("Subject");

            entity.Property(e => e.SubjectId).HasColumnName("subject_id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.SubjectCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Subject__Created__3F466844");

            entity.HasOne(d => d.ModifiedByNavigation).WithMany(p => p.SubjectModifiedByNavigations)
                .HasForeignKey(d => d.ModifiedBy)
                .HasConstraintName("FK__Subject__Modifie__403A8C7D");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.TopicId).HasName("PK__Topic__D5DAA3E92E8D418B");

            entity.ToTable("Topic");

            entity.Property(e => e.TopicId).HasColumnName("topic_id");
            entity.Property(e => e.ChapterId).HasColumnName("chapter_id");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");

            entity.HasOne(d => d.Chapter).WithMany(p => p.Topics)
                .HasForeignKey(d => d.ChapterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Topic__chapter_i__49C3F6B7");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.TopicCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Topic__CreatedBy__4AB81AF0");

            entity.HasOne(d => d.ModifiedByNavigation).WithMany(p => p.TopicModifiedByNavigations)
                .HasForeignKey(d => d.ModifiedBy)
                .HasConstraintName("FK__Topic__ModifiedB__4BAC3F29");
        });

        modelBuilder.Entity<UserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId).HasName("PK__UserAcco__DA6C70BAAB1E9BEE");

            entity.ToTable("UserAccount");

            entity.HasIndex(e => e.Email, "UQ__UserAcco__A9D10534D1EE3DCB").IsUnique();

            entity.HasIndex(e => e.UserName, "UQ__UserAcco__C9F284563CF6F593").IsUnique();

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.OtpCode).HasMaxLength(10);
            entity.Property(e => e.OtpExpiry).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.RoleId).HasDefaultValue(2);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}