// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BiologyRecognition.Domain.Entities;

public partial class ArtifactMedia
{
    public int ArtifactMediaId { get; set; }

    public int ArtifactId { get; set; }

    public string Type { get; set; }

    public string Url { get; set; }

    public string Description { get; set; }

    public virtual Artifact Artifact { get; set; }
}