// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BiologyRecognition.Domain.Entities;

public partial class Article
{
    public int ArticleId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual UserAccount ModifiedByNavigation { get; set; }

    public virtual ICollection<Artifact> Artifacts { get; set; } = new List<Artifact>();

}