// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BiologyRecognition.Domain.Entities;

public partial class Artifact
{
    public int ArtifactId { get; set; }

    public int TopicId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ScientificName { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<ArtifactImage> ArtifactImages { get; set; } = new List<ArtifactImage>();

    public virtual ICollection<ArtifactType> ArtifactTypes { get; set; } = new List<ArtifactType>();

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual UserAccount ModifiedByNavigation { get; set; }

    public virtual ICollection<Recognition> Recognitions { get; set; } = new List<Recognition>();

    public virtual Topic Topic { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}