// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BiologyRecognition.Domain.Entities;

public partial class Recognition
{
    public int RecognitionId { get; set; }

    public int? ArtifactId { get; set; }

    public int? UserId { get; set; }

    public string ImageUrl { get; set; }

    public DateTime RecognizedAt { get; set; }

    public double? ConfidenceScore { get; set; }

    public string AiResult { get; set; }

    public string Status { get; set; }

    public virtual Artifact Artifact { get; set; }

    public virtual UserAccount User { get; set; }
}